# -*- coding: utf-8 -*-
"""number_guessing_game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yMGK-XhBh2zzA71IsBfgtffphDSrEm6
"""

import random

while True:
    print('=================================')
    print('Welcome to the number guessing game!')
    print('I am thinking of a number between 1 and 100.')
    print('You have 10 attempts. Good luck!')

    secret = random.randint(1, 100)
    attempts = 0

    while True:
        try:
            guess = int(input('Enter your guess: '))
        except ValueError:
            print('Please enter a number only!')
            continue

        attempts += 1
        remaining = 10 - attempts

        if guess == secret:
            print(f'You guessed the secret number {secret} in {attempts} attempts!')
            break
        elif guess < secret:
            print(f'The secret number is higher than {guess}')
            print(f'Attempts remaining: {remaining}')
        elif guess > secret:
            print(f'The secret number is lower than {guess}')
            print(f'Attempts remaining: {remaining}')

        if attempts == 10:
            print(f'Game over! The number was {secret}')
            break

    # ✅ inside outer loop
    play_again = input('Play again? yes/no: ')
    if play_again == 'yes':
        print('Starting new game!')
    else:
        print('Thanks for playing. Goodbye!')
        break  # ✅ this stops the outer loop