# -*- coding: utf-8 -*-
"""shopping list app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3J_e5Ai4raKPUd0jbsJ3_XNiYfO7ypG
"""

shopping_list = []

def add_item(item):
  shopping_list.append(item)
  print(f'{item} added to list!')

def view_list():
  if len(shopping_list) == 0:
    print('Your list is empty!')
  else:
    print('Your shopping list:')
    for item in shopping_list:
      print(f'-{item}')
def remove_item(item):
  if item in shopping_list:
    shopping_list.remove(item)
    print(f'{item} removed!')
  else:
    print(f'{item} not found in list!')


while True:
  print('\n1. Add item')
  print('2. View list')
  print('3.Remove list')
  print('4.Quit')

  choice = input('Choose option: ')
  if choice == '1':
    item = input('Enter item: ')
    add_item(item)
  elif choice == '2':
    view_list()
  elif choice == '3':
    item = input('Enter item to remove: ')
    remove_item(item)
  elif choice == '4':
    print('Goodbye!')
    break
  else:
    print('Invalid option')